services:
  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION}
    container_name: jellyfin
    group_add:
      - "993"
    network_mode: 'host'
    volumes:
      - /config:/config
      - /cache:/cache
      - jellyfin_films:/films
      - jellyfin_shows:/shows
      - jellyfin_music:/music
    restart: 'unless-stopped'
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

volumes:
  jellyfin_films:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${TRUENAS_IP},nfsvers=4,nolock,soft,rw
      device: ":${TRUENAS_SHARE_PATH}/films"
  jellyfin_shows:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${TRUENAS_IP},nfsvers=4,nolock,soft,rw
      device: ":${TRUENAS_SHARE_PATH}/shows"
  jellyfin_music:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${TRUENAS_IP},nfsvers=4,nolock,soft,rw
      device: ":${TRUENAS_SHARE_PATH}/music"
